### ISSUE TITLE
Using an argument from a table in a hash function

### ISSUE THREAD

**Issue by TrishaDatta** [p4lang/p4c#1649]
I am trying to write a program that hashes a key retrieved from a table. I've attached the p4 file and a sample topology and switch tables. The get_key() table calls the set_key() function, which tries to hash the argument key. When I run "make run", I get the following error:

Configuring switch s3 using P4Runtime with file s3-runtime.json
 - Using P4Info file build/advanced_tunnel.p4info...
 - Connecting to P4Runtime server on 127.0.0.1:50053 (bmv2)...
 - Setting pipeline config (build/advanced_tunnel.json)...
 - Inserting 4 table entries...
 - MyIngress.ipv4_lpm: (default action) => MyIngress.drop()
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 408, in <module>
    exercise.run_exercise()
  File "../../utils/run_exercise.py", line 207, in run_exercise
    self.program_switches()
  File "../../utils/run_exercise.py", line 312, in program_switches
    self.program_switch_p4runtime(sw_name, sw_dict)
  File "../../utils/run_exercise.py", line 284, in program_switch_p4runtime
    proto_dump_fpath=outfile)
  File "/home/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 129, in program_switch
    insertTableEntry(sw, entry, p4info_helper)
  File "/home/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 150, in insertTableEntry
    sw.WriteTableEntry(table_entry)
  File "/home/p4/tutorials/utils/p4runtime_lib/switch.py", line 97, in WriteTableEntry
    self.client_stub.Write(request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 201, in __call__
    credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 225, in _with_call
    continuation, client_call_details, request)
  File "/home/p4/tutorials/utils/p4runtime_lib/switch.py", line 167, in intercept_unary_unary
    return continuation(client_call_details, request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 217, in continuation
    credentials=new_credentials)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 537, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "Socket closed"
    debug_error_string = "{"created":"@1546644964.900045017","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Socket closed","grpc_status":14}"
>
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

Is there a rule about not modifying function arguments?

[advanced_tunnel.txt](https://github.com/p4lang/p4c/files/2728888/advanced_tunnel.txt)
[s1-runtime.json.txt](https://github.com/p4lang/p4c/files/2728889/s1-runtime.json.txt)
[s2-runtime.json.txt](https://github.com/p4lang/p4c/files/2728890/s2-runtime.json.txt)
[s3-runtime.json.txt](https://github.com/p4lang/p4c/files/2728891/s3-runtime.json.txt)
[s4-runtime.json.txt](https://github.com/p4lang/p4c/files/2728892/s4-runtime.json.txt)
[s5-runtime.json.txt](https://github.com/p4lang/p4c/files/2728893/s5-runtime.json.txt)
[topology.json.txt](https://github.com/p4lang/p4c/files/2728894/topology.json.txt)

**Comment by jafingerhut** [comment]
With the latest version of p4c as of 2018-Dec-29 and the command below, there are no errors or warning messages from the compiler:
```
% p4c --target bmv2 --arch v1model advanced_tunnel.p4
```
If you try running the command above, do you see any error messages?  If so, do you know what version of the p4c compiler source you are using, and could you upgrade your version of p4c to the latest version without disrupting the rest of your development environment?

If there are no error messages from your version of p4c, then the errors you are getting appear to be coming from your code that is attempting to load the compiled P4 program into the software switch(es), and/or controller code that is attempting to configure table entries.  Such problems are likely to be outside of the P4 compiler.
