### ISSUE TITLE
SEGFAULT in p4c-bm2-ss (P4::CallGraph<...>::strongConnect)

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4c#185]
Attempting to compile the attached P4_14 program with `p4c-bm2-ss` results in a SEGFAULT.

Program: [repeater.txt](https://github.com/p4lang/p4c/files/650316/repeater.txt)

Command:
```
./p4c-bm2-ss --p4-14 repeater.txt
```

Stack trace:
```
#0  P4::CallGraph<IR::Expression const*>::strongConnect (this=this@entry=0x7fffffffc3f0, node=0xde30a0, helper=..., out=std::vector of length 0, capacity 0) at ../frontends/p4/callGraph.h:335
#1  0x0000000000671214 in sccSort (out=std::vector of length 0, capacity 0, start=<optimized out>, this=0x7fffffffc3f0) at ../frontends/p4/callGraph.h:370
#2  P4V1::ProgramStructure::createDeparser (this=this@entry=0x7fffffffc7c8) at ../frontends/p4/fromv1.0/programStructure.cpp:543
#3  0x00000000006835d3 in P4V1::ProgramStructure::create (this=0x7fffffffc7c8, info=...) at ../frontends/p4/fromv1.0/programStructure.cpp:1912
#4  0x000000000068e354 in P4V1::(anonymous namespace)::Rewriter::preorder (this=0xdabe10, global=0xdb1a00) at ../frontends/p4/fromv1.0/converters.cpp:492
#5  0x00000000006075f7 in IR::V1Program::apply_visitor_preorder (this=0xdb1a00, v=...) at ../ir/ir-inline.h:39
#6  0x0000000000649ccf in Transform::apply_visitor (this=0xdabe10, n=0xdb1460, name=<optimized out>) at ../ir/visitor.cpp:239
#7  0x000000000063b685 in visit (name=0x0, n=<synthetic pointer>, this=0xdabe30) at ../ir/visitor.h:75
#8  IR::Node::apply (this=0xdb1460, v=...) at ../ir/node.cpp:69
#9  0x000000000063c7f2 in PassManager::apply_visitor (this=0x7fffffffc780, program=0xdb1460) at ../ir/pass_manager.cpp:34
#10 0x0000000000502341 in visit (name=0x0, n=<synthetic pointer>, this=0x7fffffffd630) at ../ir/visitor.h:75
#11 parseP4File (options=...) at ../frontends/common/parseInput.cpp:39
#12 0x0000000000405cb2 in main (argc=3, argv=0x7fffffffde58) at ../backends/bmv2/bmv2.cpp:47
```

**Comment by mbudiu-vmw** [comment]
I believe that this issue has been solved.
