### ISSUE TITLE
`Compiler Bug: alias.h:246: Null result` when passing don't care (`_`) argument to action `out` parameter

### ISSUE THREAD

**Issue by kfcripps** [p4lang/p4c#4760]
```
struct S {
    bit<64> f;
}

control C(inout S s) {
    action d(in bit<64> f, out bit<64> b) {
        b = f + 4;
    }

    action foo() {
        d(s.f, _);
    }

    table t {
        actions = { foo; }
        default_action = foo;
    }

    apply {
        t.apply();
    }
}

control proto(inout S s);
package top(proto p);

top(C()) main;
```

**Comment by kfcripps** [comment]
tagging @jphurl @oleg-ran-amd

**Comment by kfcripps** [comment]
Backtrace:
```
#0  Util::CompilerBug::CompilerBug<>(int, char const*, char const*) (this=0x7ff877b249e0, line=32767, file=0x7ff877b249e0 "", format=0x7fffffffc3f0 "▒I▒w▒\177")
    at /local/kfcripps/repos/p4c/lib/exceptions.h:101
#1  0x0000555556e83478 in P4::ReadsWrites::get (this=0x7fffffffc600, expression=0x7ff877a15d20) at /local/kfcripps/repos/p4c/frontends/p4/alias.h:246
#2  0x0000555556e8362a in P4::ReadsWrites::mayAlias (this=0x7fffffffc600, left=0x7ff877a83000, right=0x7ff877a15d20) at /local/kfcripps/repos/p4c/frontends/p4/alias.h:253
#3  0x0000555557171929 in P4::DoSimplifyExpressions::mayAlias (this=0x7ff87799ea80, left=0x7ff877a83000, right=0x7ff877a15d20) at /local/kfcripps/repos/p4c/frontends/p4/sideEffects.cpp:320
#4  0x0000555557172cda in P4::DoSimplifyExpressions::preorder (this=0x7ff87799ea80, mce=0x7ff877b25780) at /local/kfcripps/repos/p4c/frontends/p4/sideEffects.cpp:466
#5  0x00005555573e8229 in IR::MethodCallExpression::apply_visitor_preorder (this=0x7ff877b25780, v=...) at /local/kfcripps/repos/p4c/ir/visitor.cpp:753
#6  0x00005555573a4195 in Transform::apply_visitor (this=0x7ff87799ea80, n=0x7ff877b08700, name=0x5555578761ff "methodCall") at /local/kfcripps/repos/p4c/ir/visitor.cpp:564
#7  0x0000555557415968 in Visitor::visit (this=0x7ff87799ec70, n=@0x7ff877b22740: 0x7ff877b08700, name=0x5555578761ff "methodCall") at /local/kfcripps/repos/p4c/ir/visitor.cpp:775
#8  0x000055555695b617 in IR::MethodCallStatement::visit_children (this=0x7ff877b22700, v=...) at /local/kfcripps/repos/p4c/build/ninja/debug/ir/ir-generated.cpp:8832
#9  0x00005555573a43a5 in Transform::apply_visitor (this=0x7ff87799ea80, n=0x7ff877b09bd0, name=0x0) at /local/kfcripps/repos/p4c/ir/visitor.cpp:586
#10 0x0000555556a1fc91 in IR::IndexedVector<IR::StatOrDecl>::visit_children (this=0x7ff877b197c8, v=...) at /local/kfcripps/repos/p4c/ir/ir-inline.h:156
#11 0x0000555556957dd0 in IR::BlockStatement::visit_children (this=0x7ff877b19780, v=...) at /local/kfcripps/repos/p4c/build/ninja/debug/ir/ir-generated.cpp:8766
#12 0x00005555573a43a5 in Transform::apply_visitor (this=0x7ff87799ea80, n=0x7ff877b06780, name=0x5555578731dd "body") at /local/kfcripps/repos/p4c/ir/visitor.cpp:586
#13 0x000055555741e662 in Visitor::visit (this=0x7ff87799ec70, n=@0x7ff877b21dc0: 0x7ff877b06780, name=0x5555578731dd "body") at /local/kfcripps/repos/p4c/ir/visitor.cpp:775
#14 0x000055555692f3d2 in IR::P4Action::visit_children (this=0x7ff877b21d20, v=...) at /local/kfcripps/repos/p4c/build/ninja/debug/ir/ir-generated.cpp:7273
#15 0x00005555573a43a5 in Transform::apply_visitor (this=0x7ff87799ea80, n=0x7ff877af9000, name=0x0) at /local/kfcripps/repos/p4c/ir/visitor.cpp:586
#16 0x0000555556a2515d in IR::IndexedVector<IR::Declaration>::visit_children (this=0x7ff877b285e0, v=...) at /local/kfcripps/repos/p4c/ir/ir-inline.h:156
#17 0x0000555556929689 in IR::P4Control::visit_children (this=0x7ff877b28540, v=...) at /local/kfcripps/repos/p4c/build/ninja/debug/ir/ir-generated.cpp:7193
#18 0x00005555573a43a5 in Transform::apply_visitor (this=0x7ff87799ea80, n=0x7ff877afb380, name=0x0) at /local/kfcripps/repos/p4c/ir/visitor.cpp:586
#19 0x0000555556a15243 in IR::Vector<IR::Node>::visit_children (this=0x7ff877b1a660, v=...) at /local/kfcripps/repos/p4c/ir/ir-inline.h:81
#20 0x0000555556950d14 in IR::P4Program::visit_children (this=0x7ff877b1a620, v=...) at /local/kfcripps/repos/p4c/build/ninja/debug/ir/ir-generated.cpp:8460
#21 0x00005555573a43a5 in Transform::apply_visitor (this=0x7ff87799ea80, n=0x7ff877b02540, name=0x0) at /local/kfcripps/repos/p4c/ir/visitor.cpp:586
#22 0x0000555556a11d48 in Visitor::visit (this=0x7ff87799ec70, n=@0x7fffffffd278: 0x7ff877b02540, name=0x0) at /local/kfcripps/repos/p4c/ir/visitor.h:121
#23 0x000055555738b070 in IR::Node::apply (this=0x7ff877b02540, v=..., ctxt=0x0) at /local/kfcripps/repos/p4c/ir/node.cpp:159
#24 0x000055555738c14b in PassManager::apply_visitor (this=0x7ff8779d1f70, program=0x7ff877b02540) at /local/kfcripps/repos/p4c/ir/pass_manager.cpp:82
#25 0x000055555738ced7 in PassRepeated::apply_visitor (this=0x7ff8779d1f00, program=0x7ff877b02540, name=0x0) at /local/kfcripps/repos/p4c/ir/pass_manager.cpp:153
#26 0x0000555556a11d48 in Visitor::visit (this=0x7ff8779d1fb8, n=@0x7fffffffd4b8: 0x7ff877b02540, name=0x0) at /local/kfcripps/repos/p4c/ir/visitor.h:121
#27 0x000055555738b070 in IR::Node::apply (this=0x7ff877b02540, v=..., ctxt=0x0) at /local/kfcripps/repos/p4c/ir/node.cpp:159
#28 0x000055555738c14b in PassManager::apply_visitor (this=0x7fffffffd740, program=0x7ff877b02540) at /local/kfcripps/repos/p4c/ir/pass_manager.cpp:82
#29 0x000055555741ca30 in Visitor::visit (this=0x7fffffffd788, n=@0x7fffffffd668: 0x7ff8779bd7e0, name=0x0) at /local/kfcripps/repos/p4c/ir/visitor.cpp:775
#30 0x0000555556950b58 in IR::P4Program::apply (this=0x7ff8779bd7e0, v=..., ctxt=0x0) at /local/kfcripps/repos/p4c/build/ninja/debug/ir/ir-generated.cpp:8447
#31 0x00005555570ce8eb in P4::FrontEnd::run (this=0x7fffffffdca0, options=..., program=0x7ff8779bd7e0, outStream=0x0) at /local/kfcripps/repos/p4c/frontends/p4/frontend.cpp:284
#32 0x0000555556ce64a9 in main (argc=4, argv=0x7fffffffe7a8) at /local/kfcripps/repos/p4c/backends/p4test/p4test.cpp:147
```
